version: "3.8"

networks:
  test-network:
    driver: bridge

services:
  backend:
    image: node:18-alpine
    container_name: test-backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: "0.0.0.0"
      CORS_ORIGIN: "*"
      # Mock service settings
      NEO4J_URI: "mock"
      NEO4J_USERNAME: "mock"
      NEO4J_PASSWORD: "mock"
      POSTGRES_HOST: "mock"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "mock"
      POSTGRES_PASSWORD: "mock"
      POSTGRES_DB: "mock"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - test-network

  frontend:
    image: node:18-alpine
    container_name: test-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5174:5173"
    volumes:
      - ./apps/frontend:/app
    working_dir: /app
    environment:
      VITE_API_URL: "http://test-backend:3000/api"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev -- --host"
    networks:
      - test-network