version: "3.8"

services:
  frontend:
    image: node:18-alpine
    container_name: rag-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      VITE_API_URL: "http://localhost:3000/api"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"