version: "3.8"

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: "neo4j/testpassword"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - neo4j
    ports:
      - "3000:3000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testpassword
    volumes:
      - ../apps/backend:/app
    working_dir: /app
    command: pnpm dev

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ../apps/frontend:/app
    working_dir: /app
    command: pnpm dev

volumes:
  neo4j_data:
  neo4j_logs:
