version: "3.8"

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      NEO4J_AUTH: "neo4j/testpassword"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./neo4j/plugins:/var/lib/neo4j/plugins
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/7687"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_DB: "ragdb"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:2.3.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 1
      AWS_DEFAULT_REGION: us-west-2
      DATA_DIR: /tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ../apps/backend/scripts:/app/scripts  # Mount init script
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "/app/scripts/init-localstack.sh && tail -f /dev/null"

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile.dev
    container_name: backend
    depends_on:
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testpassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: ragdb
    volumes:
      - ../apps/backend:/app
      - backend_nm:/app/node_modules
    working_dir: /app
    command: pnpm start:docker

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000"
    volumes:
      - ../apps/frontend:/app
      - frontend_nm:/app/node_modules
    working_dir: /app
    command: pnpm install --offline && pnpm dev

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  postgres_data:
  localstack_data:
  backend_nm:
  frontend_nm:
