FROM node:18-alpine
WORKDIR /app
RUN corepack enable

# Copy lockfile and backend manifest
COPY pnpm-lock.yaml package.json ./

# Copy source
COPY apps/backend/ .

RUN pnpm install --frozen-lockfile
EXPOSE 3000
CMD ["pnpm","start:docker"]
