version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "testpassword"
    command: pnpm dev

  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/testpassword"
