version: "3.8"

services:
  backend:
    image: node:18-alpine
    container_name: rag-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: "0.0.0.0"
      NEO4J_URI: "mock"
      NEO4J_USERNAME: "mock"
      NEO4J_PASSWORD: "mock"
      POSTGRES_HOST: "mock"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "mock"
      POSTGRES_PASSWORD: "mock"
      POSTGRES_DB: "mock"
      CORS_ORIGIN: "*"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"

  neo4j:
    image: neo4j:5.15
    container_name: rag-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/testpassword"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  postgres:
    image: postgres:15
    container_name: rag-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_DB: "ragdb"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs: